const ExcelJS = require("exceljs");
const path = require("path");
const fs = require("fs");

// Excel file path — saved in backend root folder
const EXCEL_PATH = path.join(__dirname, "../../inquiries.xlsx");

// ── Column definitions ────────────────────────────────────────────────────────
const COLUMNS = [
  { header: "S.No",          key: "sno",          width: 8  },
  { header: "First Name",    key: "firstName",    width: 16 },
  { header: "Last Name",     key: "lastName",     width: 16 },
  { header: "Email",         key: "email",        width: 30 },
  { header: "Phone",         key: "phone",        width: 18 },
  { header: "Company",       key: "company",      width: 24 },
  { header: "Practice Area", key: "practiceArea", width: 28 },
  { header: "Message",       key: "message",      width: 50 },
  { header: "Status",        key: "status",       width: 12 },
  { header: "Submitted On",  key: "createdAt",    width: 24 },
];

// ── Style helpers ─────────────────────────────────────────────────────────────
const HEADER_FILL = {
  type: "pattern", pattern: "solid",
  fgColor: { argb: "FF0D1B3E" }, // navy
};
const HEADER_FONT = {
  name: "Calibri", bold: true, color: { argb: "FFC9A84C" }, size: 11,
};
const EVEN_FILL = {
  type: "pattern", pattern: "solid",
  fgColor: { argb: "FFE8EFF8" },
};
const ODD_FILL = {
  type: "pattern", pattern: "solid",
  fgColor: { argb: "FFFFFFFF" },
};
const BORDER = {
  top:    { style: "thin", color: { argb: "FFCCCCCC" } },
  bottom: { style: "thin", color: { argb: "FFCCCCCC" } },
  left:   { style: "thin", color: { argb: "FFCCCCCC" } },
  right:  { style: "thin", color: { argb: "FFCCCCCC" } },
};

// ── Initialize workbook (create file if not exists) ────────────────────────────
const initWorkbook = async () => {
  const workbook = new ExcelJS.Workbook();

  if (fs.existsSync(EXCEL_PATH)) {
    await workbook.xlsx.readFile(EXCEL_PATH);
  } else {
    // Fresh workbook — add title sheet
    const sheet = workbook.addWorksheet("DSA Inquiries", {
      views: [{ state: "frozen", ySplit: 3 }],
    });

    // Row 1 — Title
    sheet.mergeCells("A1:J1");
    const titleCell = sheet.getCell("A1");
    titleCell.value = "DSA Corporate Solutions — Client Inquiries";
    titleCell.font = { name: "Calibri", bold: true, size: 14, color: { argb: "FF0D1B3E" } };
    titleCell.alignment = { horizontal: "center", vertical: "middle" };
    titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF5E6B8" } };
    sheet.getRow(1).height = 32;

    // Row 2 — Generated by
    sheet.mergeCells("A2:J2");
    const subCell = sheet.getCell("A2");
    subCell.value = `Generated by Janaki Digital Solutions Pvt. Ltd.  |  +977 9700227418`;
    subCell.font = { name: "Calibri", italic: true, size: 10, color: { argb: "FF555555" } };
    subCell.alignment = { horizontal: "center", vertical: "middle" };
    sheet.getRow(2).height = 20;

    // Row 3 — Headers
    sheet.columns = COLUMNS;
    const headerRow = sheet.getRow(3);
    headerRow.height = 28;
    COLUMNS.forEach((col, i) => {
      const cell = headerRow.getCell(i + 1);
      cell.value = col.header;
      cell.fill = HEADER_FILL;
      cell.font = HEADER_FONT;
      cell.alignment = { horizontal: "center", vertical: "middle" };
      cell.border = BORDER;
    });

    await workbook.xlsx.writeFile(EXCEL_PATH);
  }

  return workbook;
};

// ── Append a new inquiry row ──────────────────────────────────────────────────
const appendInquiryToExcel = async (inquiry) => {
  try {
    const workbook = await initWorkbook();
    const sheet = workbook.getWorksheet("DSA Inquiries");

    // Count existing data rows (skip title rows 1-2 and header row 3)
    const lastRow = sheet.lastRow ? sheet.lastRow.number : 3;
    const rowNum = lastRow + 1;
    const sno = rowNum - 3; // serial number

    const newRow = sheet.getRow(rowNum);
    newRow.height = 20;

    const values = {
      sno,
      firstName:    inquiry.firstName    || "",
      lastName:     inquiry.lastName     || "",
      email:        inquiry.email        || "",
      phone:        inquiry.phone        || "",
      company:      inquiry.company      || "",
      practiceArea: inquiry.practiceArea || "",
      message:      inquiry.message      || "",
      status:       inquiry.status       || "new",
      createdAt:    new Date(inquiry.createdAt).toLocaleString("en-IN", {
        timeZone: "Asia/Kathmandu",
        day: "2-digit", month: "short", year: "numeric",
        hour: "2-digit", minute: "2-digit",
      }),
    };

    COLUMNS.forEach((col, i) => {
      const cell = newRow.getCell(i + 1);
      cell.value = values[col.key];
      cell.font = { name: "Calibri", size: 10 };
      cell.border = BORDER;
      cell.alignment = {
        vertical: "middle",
        wrapText: col.key === "message",
      };
      // Alternate row colors
      cell.fill = sno % 2 === 0 ? EVEN_FILL : ODD_FILL;
    });

    // Status cell — color coded
    const statusCell = newRow.getCell(9);
    if (inquiry.status === "new") {
      statusCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFD4EDDA" } };
      statusCell.font = { ...statusCell.font, color: { argb: "FF155724" }, bold: true };
    }

    await workbook.xlsx.writeFile(EXCEL_PATH);
    console.log(`📊 Excel updated — row ${rowNum} added`);
  } catch (error) {
    console.warn("⚠️  Excel update failed:", error.message);
  }
};

// ── Export all inquiries from DB to fresh Excel ───────────────────────────────
const exportAllToExcel = async (inquiries) => {
  try {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet("DSA Inquiries", {
      views: [{ state: "frozen", ySplit: 3 }],
    });

    // Title row
    sheet.mergeCells("A1:J1");
    const titleCell = sheet.getCell("A1");
    titleCell.value = "DSA Corporate Solutions — All Client Inquiries";
    titleCell.font = { name: "Calibri", bold: true, size: 14, color: { argb: "FF0D1B3E" } };
    titleCell.alignment = { horizontal: "center", vertical: "middle" };
    titleCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: "FFF5E6B8" } };
    sheet.getRow(1).height = 32;

    // Subtitle
    sheet.mergeCells("A2:J2");
    const subCell = sheet.getCell("A2");
    subCell.value = `Exported on: ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kathmandu" })}  |  Total: ${inquiries.length} inquiries`;
    subCell.font = { name: "Calibri", italic: true, size: 10, color: { argb: "FF555555" } };
    subCell.alignment = { horizontal: "center" };
    sheet.getRow(2).height = 20;

    // Headers
    sheet.columns = COLUMNS;
    const headerRow = sheet.getRow(3);
    headerRow.height = 28;
    COLUMNS.forEach((col, i) => {
      const cell = headerRow.getCell(i + 1);
      cell.value = col.header;
      cell.fill = HEADER_FILL;
      cell.font = HEADER_FONT;
      cell.alignment = { horizontal: "center", vertical: "middle" };
      cell.border = BORDER;
    });

    // Data rows
    inquiries.forEach((inq, idx) => {
      const rowNum = idx + 4;
      const row = sheet.getRow(rowNum);
      row.height = 20;

      const values = {
        sno:          idx + 1,
        firstName:    inq.firstName    || "",
        lastName:     inq.lastName     || "",
        email:        inq.email        || "",
        phone:        inq.phone        || "",
        company:      inq.company      || "",
        practiceArea: inq.practiceArea || "",
        message:      inq.message      || "",
        status:       inq.status       || "new",
        createdAt:    new Date(inq.createdAt).toLocaleString("en-IN", {
          timeZone: "Asia/Kathmandu",
          day: "2-digit", month: "short", year: "numeric",
          hour: "2-digit", minute: "2-digit",
        }),
      };

      COLUMNS.forEach((col, i) => {
        const cell = row.getCell(i + 1);
        cell.value = values[col.key];
        cell.font = { name: "Calibri", size: 10 };
        cell.border = BORDER;
        cell.alignment = { vertical: "middle", wrapText: col.key === "message" };
        cell.fill = (idx + 1) % 2 === 0 ? EVEN_FILL : ODD_FILL;
      });

      // Color code status
      const statusCell = row.getCell(9);
      const statusColors = {
        new:     { bg: "FFD4EDDA", fg: "FF155724" },
        read:    { bg: "FFCCE5FF", fg: "FF004085" },
        replied: { bg: "FFFFF3CD", fg: "FF856404" },
        closed:  { bg: "FFF8D7DA", fg: "FF721C24" },
      };
      const sc = statusColors[inq.status] || statusColors.new;
      statusCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: sc.bg } };
      statusCell.font = { name: "Calibri", size: 10, color: { argb: sc.fg }, bold: true };
    });

    // Return buffer for download
    const buffer = await workbook.xlsx.writeBuffer();
    return buffer;
  } catch (error) {
    console.error("Excel export error:", error);
    throw error;
  }
};

module.exports = { appendInquiryToExcel, exportAllToExcel, EXCEL_PATH };
